services:
  service:
    cpuset: 0,1
    build: .
    ports:
      - "4040:4040"
    depends_on:
      - db
    links:
      - db
    restart: always
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_ADDRESS: db
  db:
    ports:
      - "27017:27017"
    image: mongo
    restart: always
    environment:
      TZ: America/Sao_Paulo 
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
